// Generated by https://jvilk.com/MakeTypes/

export interface MarketManager {
    market?: string,
    setMarket: React.Dispatch<React.SetStateAction<string>>,
    setData: React.Dispatch<React.SetStateAction<any>>
}

export interface Slides {
    hero: Hero;
    slides: SlidesEntity[];
    topSales: TopSales;
}

export interface Data {
    data: SlidesEntity[]
}

export interface Hero {
    image?: (ImageEntity)[] | null;
    title: string;
}
export interface ImageEntity {
    url: string;
    text: string;
}
export interface SlidesEntity {
    name: string;
    description: string;
    slug: string;
    type: string;
    title: string;
    icon: string;
    background: string;
    cards?: (CardsEntity)[] | null;
    totalCampaigns?: number | null;
}
export interface CardsEntity {
    id?: number;
    title: string;
    destination: string;
    images: (ImagesEntity)[];
    days: number;
    url?: string;
    map?: null;
    highlights?: null;
    includes?: null;
    priceDetail: PriceDetail;
    tags?: null;
    crafterDetail?: null;
    hasPrivateTour?: boolean;
    hasSoloTraveller?: boolean;
    headLine?: null;
    tagHeadLine?: (null)[] | null;
    isLandOnly?: boolean;
    isValid?: boolean;
    extraNights?: number;
}
export interface ImagesEntity {
    desktop: string;
    tablet: string;
    mobile: string;
}
export interface PriceDetail {
    fromPrice: number;
    fromPriceBeautify: string;
    discountSaved: number;
    oldPriceBeautify: string;
    pricingPercentage: number;
    pricePerNight: string;
}
export interface TopSales {
    type: string;
    title: string;
    icon: string;
    background: string;
    cards?: (CardsEntity)[] | null;
}
